{
  "info": {
    "author": "Thomas Aglassinger",
    "author_email": "roskakori@users.sourceforge.net",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 4 - Beta",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: BSD License",
      "Natural Language :: English",
      "Operating System :: OS Independent",
      "Programming Language :: Python :: 3 :: Only",
      "Programming Language :: Python :: 3.10",
      "Programming Language :: Python :: 3.6",
      "Programming Language :: Python :: 3.7",
      "Programming Language :: Python :: 3.8",
      "Programming Language :: Python :: 3.9",
      "Topic :: Software Development"
    ],
    "description": "# errortext\n\n`errortext` is a Python package to provide error messages for Python\nexceptions, even if the original message is empty.\n\nAs example consider the following function that might fail in different ways:\n\n```python\nfrom errortext import error_text\n\ndef do_something(action_to_perform):\n    if action_to_perform == \"walk\":\n        print(\"walking\")\n    elif action_to_perform == \"sleep\":\n        raise ValueError(\"must be tired in order to sleep\")\n    elif action_to_perform == \"run\":\n        raise NotImplementedError(\"run\")\n    else:\n        assert False\n```\n\nOne could use the following code to run this function and print possible\nerror details by using the error message of the exception from\n`str(error)`:\n\n```python\ntry:\n    do_something(action)\n    print(f\"Success: done with {action}\")\nexcept Exception as error:\n    print(f\"Error: cannot {action}: {str(error)}\")\n```\n\nAs you notice, some error will not have any meaningful message:\n\n```\ndo_something(\"sleep\") -> cannot sleep: must be tired in order to sleep\ndo_something(\"run\")   -> cannot run: run\ndo_something(\"xxx\")   -> cannot xxx:\n```\n\nNo change the error handler to:\n\n```python\nprint(f\"Error with error_text: cannot {action}: {error_text(error)}\")\n```\n\nThe error messages will at least contain some hint at what went wrong:\n\n```\ndo_something(\"sleep\") -> cannot sleep: must be tired in order to sleep\ndo_something(\"run\")   -> cannot run: NotImplementedError: run\ndo_something(\"xxx\")   -> cannot xxx: AssertionError\n```\n\n\n",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/roskakori/errortext",
    "keywords": "error,error handling,error message,exception,exception handling",
    "license": "BSD",
    "maintainer": "",
    "maintainer_email": "",
    "name": "errortext",
    "package_url": "https://pypi.org/project/errortext/",
    "platform": "",
    "project_url": "https://pypi.org/project/errortext/",
    "project_urls": {
      "Changes": "https://github.com/roskakori/errortext/blob/main/CHANGES.md",
      "Homepage": "https://github.com/roskakori/errortext",
      "Issue Tracker": "https://github.com/roskakori/errortext/issues"
    },
    "release_url": "https://pypi.org/project/errortext/0.1.0/",
    "requires_dist": null,
    "requires_python": ">=3.6",
    "summary": "Provide error messages for Python exceptions, even if the original message is empty",
    "version": "0.1.0",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 12236935,
  "releases": {
    "0.1.0": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "b384bc4fa95bf6f994485e1c1241d02e93bb600be66d024e6b4febe0864d749a",
          "md5": "d48d49e7dda8c7af8ea04ca0a7e41a98",
          "sha256": "330ad6ec71f274feccc7483ee3ca3a77a42684f0acc234fe9f0f7da7ec3d631f"
        },
        "downloads": -1,
        "filename": "errortext-0.1.0-py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "d48d49e7dda8c7af8ea04ca0a7e41a98",
        "packagetype": "bdist_wheel",
        "python_version": "py3",
        "requires_python": ">=3.6",
        "size": 3781,
        "upload_time": "2021-12-07T18:34:04",
        "upload_time_iso_8601": "2021-12-07T18:34:04.059487Z",
        "url": "https://files.pythonhosted.org/packages/b3/84/bc4fa95bf6f994485e1c1241d02e93bb600be66d024e6b4febe0864d749a/errortext-0.1.0-py3-none-any.whl",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "b384bc4fa95bf6f994485e1c1241d02e93bb600be66d024e6b4febe0864d749a",
        "md5": "d48d49e7dda8c7af8ea04ca0a7e41a98",
        "sha256": "330ad6ec71f274feccc7483ee3ca3a77a42684f0acc234fe9f0f7da7ec3d631f"
      },
      "downloads": -1,
      "filename": "errortext-0.1.0-py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "d48d49e7dda8c7af8ea04ca0a7e41a98",
      "packagetype": "bdist_wheel",
      "python_version": "py3",
      "requires_python": ">=3.6",
      "size": 3781,
      "upload_time": "2021-12-07T18:34:04",
      "upload_time_iso_8601": "2021-12-07T18:34:04.059487Z",
      "url": "https://files.pythonhosted.org/packages/b3/84/bc4fa95bf6f994485e1c1241d02e93bb600be66d024e6b4febe0864d749a/errortext-0.1.0-py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}