{
  "info": {
    "author": "Hyppoprogramm",
    "author_email": "programm.jeremiah@yandex.ru",
    "bugtrack_url": null,
    "classifiers": [
      "License :: OSI Approved :: MIT License",
      "Operating System :: OS Independent",
      "Programming Language :: Python :: 3"
    ],
    "description": "# PyError\n## Exception management package\n\nThis package allows you to quickly create and manage exceptions\n\n## Installation\n\n> pip install PyErrManager\n\n## Example\n\n```python\nfrom pyerror.templates import TypeError\ndef add(a,b):\n\tif type(a) != int or type(b) != int:\n\t\tTypeError.unsupported_operand_types('+',a.__class__.__name__,b.__class__.__name__)(end=-1);\n\treturn a+b;\nprint(add(1,2))\nprint(add('1',2))\n```\n\n\n",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "",
    "keywords": "",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "PyErrManager",
    "package_url": "https://pypi.org/project/PyErrManager/",
    "platform": "",
    "project_url": "https://pypi.org/project/PyErrManager/",
    "project_urls": null,
    "release_url": "https://pypi.org/project/PyErrManager/2.0/",
    "requires_dist": null,
    "requires_python": ">=3.6",
    "summary": "Exception management package",
    "version": "2.0",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 6521267,
  "releases": {
    "2.0": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "a45ea779659d1a4b63ce259940f00a8b1b6e0e9ae4e462cf4bbcbb9c7de717a4",
          "md5": "86871c26808b822528ce237dbae1db73",
          "sha256": "9d4c80c8f50fa121b7cf629789d1fb95f19de5b3f4b8503f878e00759cfce35c"
        },
        "downloads": -1,
        "filename": "PyErrManager-2.0-py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "86871c26808b822528ce237dbae1db73",
        "packagetype": "bdist_wheel",
        "python_version": "py3",
        "requires_python": ">=3.6",
        "size": 5174,
        "upload_time": "2020-01-26T08:47:41",
        "upload_time_iso_8601": "2020-01-26T08:47:41.125487Z",
        "url": "https://files.pythonhosted.org/packages/a4/5e/a779659d1a4b63ce259940f00a8b1b6e0e9ae4e462cf4bbcbb9c7de717a4/PyErrManager-2.0-py3-none-any.whl",
        "yanked": false,
        "yanked_reason": null
      },
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "c0b443326faa132bf7a8c34fef38f67def09011a3aeeebc79466120b32c387f7",
          "md5": "874f128520ee19125f338b7803706894",
          "sha256": "7b6d34e551fdaf2574f95e676cc8b34e44e6057f355372e6d12d4ab621a8a8b2"
        },
        "downloads": -1,
        "filename": "PyErrManager-2.0.tar.gz",
        "has_sig": false,
        "md5_digest": "874f128520ee19125f338b7803706894",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": ">=3.6",
        "size": 3906,
        "upload_time": "2020-01-26T08:47:42",
        "upload_time_iso_8601": "2020-01-26T08:47:42.861835Z",
        "url": "https://files.pythonhosted.org/packages/c0/b4/43326faa132bf7a8c34fef38f67def09011a3aeeebc79466120b32c387f7/PyErrManager-2.0.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "a45ea779659d1a4b63ce259940f00a8b1b6e0e9ae4e462cf4bbcbb9c7de717a4",
        "md5": "86871c26808b822528ce237dbae1db73",
        "sha256": "9d4c80c8f50fa121b7cf629789d1fb95f19de5b3f4b8503f878e00759cfce35c"
      },
      "downloads": -1,
      "filename": "PyErrManager-2.0-py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "86871c26808b822528ce237dbae1db73",
      "packagetype": "bdist_wheel",
      "python_version": "py3",
      "requires_python": ">=3.6",
      "size": 5174,
      "upload_time": "2020-01-26T08:47:41",
      "upload_time_iso_8601": "2020-01-26T08:47:41.125487Z",
      "url": "https://files.pythonhosted.org/packages/a4/5e/a779659d1a4b63ce259940f00a8b1b6e0e9ae4e462cf4bbcbb9c7de717a4/PyErrManager-2.0-py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "c0b443326faa132bf7a8c34fef38f67def09011a3aeeebc79466120b32c387f7",
        "md5": "874f128520ee19125f338b7803706894",
        "sha256": "7b6d34e551fdaf2574f95e676cc8b34e44e6057f355372e6d12d4ab621a8a8b2"
      },
      "downloads": -1,
      "filename": "PyErrManager-2.0.tar.gz",
      "has_sig": false,
      "md5_digest": "874f128520ee19125f338b7803706894",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": ">=3.6",
      "size": 3906,
      "upload_time": "2020-01-26T08:47:42",
      "upload_time_iso_8601": "2020-01-26T08:47:42.861835Z",
      "url": "https://files.pythonhosted.org/packages/c0/b4/43326faa132bf7a8c34fef38f67def09011a3aeeebc79466120b32c387f7/PyErrManager-2.0.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}