{
  "info": {
    "author": "NAGY, Attila",
    "author_email": "nagy.attila+pytest@gmail.com",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Framework :: Pytest",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 2",
      "Programming Language :: Python :: 3"
    ],
    "description": "====================================\npytest-unhandled-exception-exit-code\n====================================\n\nPlugin for ``pytest`` to change exit code on uncaught exceptions\n\n* Free software: MIT license\n\nFeatures\n--------\n\n* You can set a different exit code when uncaught exceptions in ``pytest`` test\n  cases will occur\n\n\nInstallation\n------------\n\nYou can install the plugin by running\n\n    pip install pytest-unhandled-exception-exit-code\n\nAlternately check out the source code and run\n\n    python setup.py install\n\n\nUsage\n-----\n\nIf you want to change `pytest` exit code to detect unhandled exceptions in\ntests, give the plugin the desired exit code with the following option:\n``pytest --unhandled-exc-exit-code 13``\n\n\n\n",
    "description_content_type": "",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/bra-fsn/pytest-unhandled-exception-exit-code",
    "keywords": "pytest,py.test",
    "license": "BSD",
    "maintainer": "",
    "maintainer_email": "",
    "name": "pytest-unhandled-exception-exit-code",
    "package_url": "https://pypi.org/project/pytest-unhandled-exception-exit-code/",
    "platform": "",
    "project_url": "https://pypi.org/project/pytest-unhandled-exception-exit-code/",
    "project_urls": {
      "Homepage": "https://github.com/bra-fsn/pytest-unhandled-exception-exit-code"
    },
    "release_url": "https://pypi.org/project/pytest-unhandled-exception-exit-code/0.0.2/",
    "requires_dist": [
      "pytest (>=2.3)"
    ],
    "requires_python": "",
    "summary": "Plugin for py.test set a different exit code on uncaught exceptions",
    "version": "0.0.2",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 7533092,
  "releases": {
    "0.0.1": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "5ca5fd52e996edeb02c0b9f10f997f1b47a54ca8858969b6d7a09858613cabc5",
          "md5": "d511058e072c8f44f04bae78626160c9",
          "sha256": "c7a6935c9341e2870cfffa307858400b0e23015810eccd3bef9a886620bd59dd"
        },
        "downloads": -1,
        "filename": "pytest-unhandled-exception-exit-code-0.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "d511058e072c8f44f04bae78626160c9",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": null,
        "size": 2419,
        "upload_time": "2020-06-22T10:12:23",
        "upload_time_iso_8601": "2020-06-22T10:12:23.809272Z",
        "url": "https://files.pythonhosted.org/packages/5c/a5/fd52e996edeb02c0b9f10f997f1b47a54ca8858969b6d7a09858613cabc5/pytest-unhandled-exception-exit-code-0.0.1.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ],
    "0.0.2": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "e9a583844a2e2babf0bbbf068e4af96f3d2139a201de5d18018eb797706f858c",
          "md5": "9e6f6a1cf3bc78ad2b0f1e3f35caf20d",
          "sha256": "5d1527e30ec7f79118ce0f97dfc937819eb48f85d07f0da4f241081157353bfe"
        },
        "downloads": -1,
        "filename": "pytest_unhandled_exception_exit_code-0.0.2-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "9e6f6a1cf3bc78ad2b0f1e3f35caf20d",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "requires_python": null,
        "size": 3633,
        "upload_time": "2020-06-22T10:21:26",
        "upload_time_iso_8601": "2020-06-22T10:21:26.694136Z",
        "url": "https://files.pythonhosted.org/packages/e9/a5/83844a2e2babf0bbbf068e4af96f3d2139a201de5d18018eb797706f858c/pytest_unhandled_exception_exit_code-0.0.2-py2.py3-none-any.whl",
        "yanked": false,
        "yanked_reason": null
      },
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "746e45e3ee7c9ec4d83f1c0d99f915bfe7051b952ae9119e7dd4ed5499a5ac9f",
          "md5": "bdd92e255db973a281cf5265befb8485",
          "sha256": "65272027f42f6dc58f5418c1203cc023a6ef305774918c3cf0e0023bbababc09"
        },
        "downloads": -1,
        "filename": "pytest-unhandled-exception-exit-code-0.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "bdd92e255db973a281cf5265befb8485",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": null,
        "size": 2387,
        "upload_time": "2020-06-22T10:21:27",
        "upload_time_iso_8601": "2020-06-22T10:21:27.544053Z",
        "url": "https://files.pythonhosted.org/packages/74/6e/45e3ee7c9ec4d83f1c0d99f915bfe7051b952ae9119e7dd4ed5499a5ac9f/pytest-unhandled-exception-exit-code-0.0.2.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "e9a583844a2e2babf0bbbf068e4af96f3d2139a201de5d18018eb797706f858c",
        "md5": "9e6f6a1cf3bc78ad2b0f1e3f35caf20d",
        "sha256": "5d1527e30ec7f79118ce0f97dfc937819eb48f85d07f0da4f241081157353bfe"
      },
      "downloads": -1,
      "filename": "pytest_unhandled_exception_exit_code-0.0.2-py2.py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "9e6f6a1cf3bc78ad2b0f1e3f35caf20d",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "requires_python": null,
      "size": 3633,
      "upload_time": "2020-06-22T10:21:26",
      "upload_time_iso_8601": "2020-06-22T10:21:26.694136Z",
      "url": "https://files.pythonhosted.org/packages/e9/a5/83844a2e2babf0bbbf068e4af96f3d2139a201de5d18018eb797706f858c/pytest_unhandled_exception_exit_code-0.0.2-py2.py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "746e45e3ee7c9ec4d83f1c0d99f915bfe7051b952ae9119e7dd4ed5499a5ac9f",
        "md5": "bdd92e255db973a281cf5265befb8485",
        "sha256": "65272027f42f6dc58f5418c1203cc023a6ef305774918c3cf0e0023bbababc09"
      },
      "downloads": -1,
      "filename": "pytest-unhandled-exception-exit-code-0.0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "bdd92e255db973a281cf5265befb8485",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 2387,
      "upload_time": "2020-06-22T10:21:27",
      "upload_time_iso_8601": "2020-06-22T10:21:27.544053Z",
      "url": "https://files.pythonhosted.org/packages/74/6e/45e3ee7c9ec4d83f1c0d99f915bfe7051b952ae9119e7dd4ed5499a5ac9f/pytest-unhandled-exception-exit-code-0.0.2.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}