{
  "info": {
    "author": "Justin Driscoll, Marcos Daniel Petry, Richard Barran",
    "author_email": "justin@driscolldev.com, marcospetry@gmail.com, richard@arbee-design.co.uk",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Environment :: Web Environment",
      "Framework :: Django",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: BSD License",
      "Operating System :: OS Independent",
      "Programming Language :: Python",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.3",
      "Programming Language :: Python :: 3.4",
      "Programming Language :: Python :: 3.5",
      "Topic :: Utilities"
    ],
    "description": "UNKNOWN\n\n\n",
    "description_content_type": null,
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/jdriscoll/django-photologue",
    "keywords": "",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "django-photologue",
    "package_url": "https://pypi.org/project/django-photologue/",
    "platform": "",
    "project_url": "https://pypi.org/project/django-photologue/",
    "project_urls": {
      "Homepage": "https://github.com/jdriscoll/django-photologue"
    },
    "release_url": "https://pypi.org/project/django-photologue/3.7/",
    "requires_dist": [
      "Django (>=1.8)",
      "ExifRead (>=2.1.2)",
      "Pillow (>=2.7.0)",
      "django-sortedm2m (>=1.3.3)"
    ],
    "requires_python": "",
    "summary": "Powerful image management for the Django web framework.",
    "version": "3.7",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 12981258,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "259a42459f76c57103788e8a917e77a28f1898f9b9d10b2238ac1cdcc1cf5acc",
        "md5": "8da63a7f2dea1b95e240de622a3b963d",
        "sha256": "8ad20fb57cc67cc5b4d0961276a8493734d6aebee3ee9b1749b4c0cb8decab65"
      },
      "downloads": -1,
      "filename": "django_photologue-3.7-py2.py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "8da63a7f2dea1b95e240de622a3b963d",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "requires_python": null,
      "size": 297243,
      "upload_time": "2017-05-10T17:02:38",
      "upload_time_iso_8601": "2017-05-10T17:02:38.121656Z",
      "url": "https://files.pythonhosted.org/packages/25/9a/42459f76c57103788e8a917e77a28f1898f9b9d10b2238ac1cdcc1cf5acc/django_photologue-3.7-py2.py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "dde38f32d83ce67cc82c361241c699fc8dac6762849108f0e22296f91d8322e8",
        "md5": "771da98e6ae98746633a97ab3659c685",
        "sha256": "3e13ac55fbcf0d68b2b8c6aba32aa9b8e369b42d844364d3033ae9573809d3b7"
      },
      "downloads": -1,
      "filename": "django-photologue-3.7.tar.gz",
      "has_sig": false,
      "md5_digest": "771da98e6ae98746633a97ab3659c685",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 159732,
      "upload_time": "2017-05-10T17:02:39",
      "upload_time_iso_8601": "2017-05-10T17:02:39.961258Z",
      "url": "https://files.pythonhosted.org/packages/dd/e3/8f32d83ce67cc82c361241c699fc8dac6762849108f0e22296f91d8322e8/django-photologue-3.7.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": [
    {
      "aliases": [
        "CVE-2022-4526"
      ],
      "details": "A vulnerability was found in django-photologue up to 3.15.1 and classified as problematic. Affected by this issue is some unknown functionality of the file photologue/templates/photologue/photo_detail.html of the component Default Template Handler. The manipulation of the argument object.caption leads to cross site scripting. The attack may be launched remotely. Upgrading to version 3.16 is able to address this issue. The name of the patch is 960cb060ce5e2964e6d716ff787c72fc18a371e7. It is recommended to apply a patch to fix this issue. VDB-215906 is the identifier assigned to this vulnerability.",
      "fixed_in": [],
      "id": "GHSA-287q-jfcp-9vhv",
      "link": "https://osv.dev/vulnerability/GHSA-287q-jfcp-9vhv",
      "source": "osv",
      "summary": null,
      "withdrawn": null
    }
  ]
}