{
  "info": {
    "author": "Gustavo Selbach Teixeira",
    "author_email": "gsteixei@gmail.com",
    "bugtrack_url": null,
    "classifiers": [
      "Environment :: Web Environment",
      "Framework :: Django"
    ],
    "description": " DJANGO EXCEPT CATCHER\n------------------------\n\ndjango-except-catcher is a simple tool to catch and store exceptions and _500 errors_ in production django applications.\n\n![django-except-catcher Logo](/except_catcher/static/except_catcher/logo.png)\n\nWhen a _500 error_ happens a record with the details is stored in the database.\n\nExceptions are stored and listed so you can find similar errors and look their \"yellow error page\", just like in django's debug mode.\n\nIt doesn't require to run any daemon in order to work, just install a regular django module.\n\nInspired by django's AdminMailHandler.\n\nFor an example out of the box, take a look [here](https://github.com/gsteixeira/django-except-catcher-demo).\n\nINSTALLATION\n-------------\n\nInstall django-except-catcher:\n\n```shell\n   pip install django-except-catcher\n\n```\n\nAdd to urls.py:\n\n```python\n   path('', include(('except_catcher.urls', 'except_catcher'), namespace=\"except_catcher\"))\n\n```\nadd to settings.py:\n\n```python\n    INSTALLED_APPS = [\n        ...\n        'except_catcher',\n    ]\n\n    LOGGING = {\n        'version': 1,\n        'handlers': {\n                'error_catcher': {\n                'level': 'ERROR',\n                'class': 'except_catcher.handlers.CatchExceptionHandler',\n            },\n        },\n        'loggers': {\n            'django.request': {\n                'handlers': [ 'error_catcher'],\n                'level': 'ERROR',\n                'propagate': False,\n            },\n        }\n    }\n\n```\n\nrun migrations:\n\n```shell\n   ./manage.py migrate except_catcher\n\n```\n\nYou can purposely throw an exception in the url (must be superuser):\n\n    http://localhost:8000/test-exception/\n\nNow go to url:\n\n    http://localhost:8000/errors/\n\nOnly the superuser have access to these reports.\n\n\n\n\n",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/gsteixeira/django-except-catcher",
    "keywords": "",
    "license": "GNU License",
    "maintainer": "",
    "maintainer_email": "",
    "name": "django-except-catcher",
    "package_url": "https://pypi.org/project/django-except-catcher/",
    "platform": "",
    "project_url": "https://pypi.org/project/django-except-catcher/",
    "project_urls": {
      "Homepage": "https://github.com/gsteixeira/django-except-catcher"
    },
    "release_url": "https://pypi.org/project/django-except-catcher/1.0.1/",
    "requires_dist": null,
    "requires_python": "",
    "summary": "Catch Exceptions in production",
    "version": "1.0.1",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 12423905,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "87776dd9026457b98367fd0af4e4f459d1a57bd3026bf4b0e2b7d553d8e4b64f",
        "md5": "bd03f822682ed90a0965dd379bff9bd0",
        "sha256": "bf5b3f22476a48639a4ae169683fbda39d6ca8e1db3cc0eda3cd6495010658d1"
      },
      "downloads": -1,
      "filename": "django-except-catcher-1.0.1.tar.gz",
      "has_sig": false,
      "md5_digest": "bd03f822682ed90a0965dd379bff9bd0",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 32549,
      "upload_time": "2021-12-28T16:32:17",
      "upload_time_iso_8601": "2021-12-28T16:32:17.859089Z",
      "url": "https://files.pythonhosted.org/packages/87/77/6dd9026457b98367fd0af4e4f459d1a57bd3026bf4b0e2b7d553d8e4b64f/django-except-catcher-1.0.1.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}