{
  "info": {
    "author": "",
    "author_email": "",
    "bugtrack_url": null,
    "classifiers": [
      "Framework :: Django",
      "License :: Public Domain",
      "Operating System :: OS Independent",
      "Programming Language :: Python :: 3"
    ],
    "description": "<!--\nhttps://readme42.com\n-->\n\n\n[![](https://img.shields.io/pypi/v/django-traceback.svg?maxAge=3600)](https://pypi.org/project/django-traceback/)\n[![](https://img.shields.io/badge/License-Unlicense-blue.svg?longCache=True)](https://unlicense.org/)\n\n### Installation\n```bash\n$ [sudo] pip install django-traceback\n```\n\n#### Examples\n```python\nfrom django_traceback.utils import save_traceback\nimport requests\nfrom apps.celery import celery_app\n\n@celery_app.task\ndef task():\n    try:\n        r = requests.get('url')\n    except (requests.exceptions.ConnectionError,...):\n        save_traceback(__file__)\n        # init task again\n```\n\n<p align=\"center\">\n    <a href=\"https://readme42.com/\">readme42.com</a>\n</p>",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/andrewp-as-is/django-traceback.py",
    "keywords": "django traceback",
    "license": "Unlicense",
    "maintainer": "",
    "maintainer_email": "",
    "name": "django-traceback",
    "package_url": "https://pypi.org/project/django-traceback/",
    "platform": "",
    "project_url": "https://pypi.org/project/django-traceback/",
    "project_urls": {
      "Homepage": "https://github.com/andrewp-as-is/django-traceback.py"
    },
    "release_url": "https://pypi.org/project/django-traceback/2020.12.3/",
    "requires_dist": null,
    "requires_python": "",
    "summary": "Traceback model and utils",
    "version": "2020.12.3",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 8814744,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "6e9116c7acb4ab5801a1ddbd6bc469daa5157b0ff036ae5cbb4f1ddb1295f2b8",
        "md5": "cb9dfeb0c439bdf110eff6896ef299f9",
        "sha256": "a8ceb75aaa9142ec7083a65a4da841d7795ce3964ede272dadd42877bd1385fa"
      },
      "downloads": -1,
      "filename": "django-traceback-2020.12.3.tar.gz",
      "has_sig": false,
      "md5_digest": "cb9dfeb0c439bdf110eff6896ef299f9",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 2251,
      "upload_time": "2020-12-03T20:23:24",
      "upload_time_iso_8601": "2020-12-03T20:23:24.665892Z",
      "url": "https://files.pythonhosted.org/packages/6e/91/16c7acb4ab5801a1ddbd6bc469daa5157b0ff036ae5cbb4f1ddb1295f2b8/django-traceback-2020.12.3.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}