{
  "info": {
    "author": "Chad Rosenquist",
    "author_email": "chadrosenquist@gmail.com",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "\nlogging-test-case\n=================\n\nProduction systems rely heavily upon logging. Unit tests should verify\nlogs are correct. ``unittest.assertLogs()`` allows developers to verify\nlogs are correct. Including this context manager in every test case\nbecomes tiresome. Also, if the test fails, the logs are not displayed.\n\nThis project provides the function decorator ``@capturelogs``.\n``@capturelogs`` is similar to ``unittest.assertLogs()``, but it is a\nfunction decorator, reducing the clutter inside the test function.\n\nThis project provides the class ``LoggingTestCase``, which inherits from\n``unittest.TestCase``. For every test run, logs are automatically\ncaptured to ``self.captured_logs``. If the test fails, the contents of\n``self.captured_logs`` are written to the test output for easy\ndebugging.  ``LoggingTestCase`` provides context manager ``assertNoLogs``\nto verify no logs were emitted within the context.\n\n-  Use ``@capturelogs`` if only a few tests involve log files.\n-  Use ``LoggingTestCase`` if most of the tests involve logs. This\n   avoids putting a function decorator for each function.\n\nInstallation\n============\n\nThis package is at pypi at:\n\nhttps://pypi.python.org/pypi/logging-test-case\n\nTo install using pip:\n\n``pip install logging-test-case``\n\nRequirements\n============\n\n-  Python 3.4 or higher.\n\n@capturelogs\n============\n\n``capturelogs(logger=None, level=None, display_logs=DisplayLogs.FAILURE, assert_no_logs=False)``\n\n* logger: Name of logger, or an actual logger. Defaults to root logger.\n* level: Log level as a text string. Defaults to 'INFO'.\n* display_logs: Determines when to display logs\n    - DisplayLogs.NEVER: Never display the logs. The logs will always be discarded.\n        + This is the current behavior of ``unittest.assertLogs()``.\n    - DisplayLogs.FAILURE: Display the logs only if the test case fails. (default)\n        + This can be useful for debugging test failures because the logs are still written out.\n    - DisplayLogs.ALWAYS: Always displays the logs - pass or fail.\n        + This can be useful when manually running the tests and the developer wants to visually inspect the logging output.\n* assert_no_logs: If True, raise an AssertionError if any logs are emitted.\n\nExamples are located at: ``examples/capturelogs_example.py``\n\nunittest.assertLogs example\n---------------------------\n\n::\n\n    class CaptureLogsExample(unittest.TestCase):\n        def test_assert_logs(self):\n            \"\"\"Verify logs using built-in self.assertLogs().\"\"\"\n            with self.assertLogs('foo', level='INFO') as logs:\n                logging.getLogger('foo').info('first message')\n                logging.getLogger('foo.bar').error('second message')\n            self.assertEqual(logs.output, ['INFO:foo:first message',\n                                           'ERROR:foo.bar:second message'])\n\n@capturelogs example\n--------------------\n\n::\n\n    import unittest\n    import logging\n\n    import loggingtestcase\n\n\n    class CaptureLogsExample(unittest.TestCase):\n        @loggingtestcase.capturelogs('foo', level='INFO')\n        def test_capture_logs(self, logs):\n            \"\"\"Verify logs using @capturelogs decorator.\"\"\"\n            logging.getLogger('foo').info('first message')\n            logging.getLogger('foo.bar').error('second message')\n\n            self.assertEqual(logs.output, ['INFO:foo:first message',\n                                           'ERROR:foo.bar:second message'])\n\nIn the above example, there is less clutter and indenting inside of the\ntest function. For this simple example, it doesn't matter. But if the\ntest involves multiple patches and ``self.assertRaises`` and many other\ncontext managers, the function becomes crowded very quickly. The\n``@capturelogs`` function decorator allows the developer to reduce the\ncontents and indent level inside of the function.\n\n@capturelogs display example\n----------------------------\n\n::\n\n    import unittest\n    import logging\n\n    import loggingtestcase\n\n\n    class CaptureLogsExample(unittest.TestCase):\n        @loggingtestcase.capturelogs('foo', level='INFO',\n                                     display_logs=loggingtestcase.DisplayLogs.ALWAYS)\n        def test_always_display_logs(self, logs):\n            \"\"\"The logs are always written to the original handler(s).\"\"\"\n            logging.getLogger('foo').info('first message')\n            self.assertTrue(False)\n            self.assertEqual(logs.output, ['INFO:foo:first message'])\n\nIn the above example, the test fails, the logs are be displayed.\n\n@capturelogs assert_no_logs example\n-----------------------------------\n\n::\n\n    import unittest\n    import logging\n\n    import loggingtestcase\n\n\n    class CaptureLogsExample(unittest.TestCase):\n        @loggingtestcase.capturelogs('foo', level='INFO', assert_no_logs=True)\n        def test_assert_no_logs(self, logs):\n            \"\"\"This test fails because logs are emitted.\n\n            Output::\n\n                AssertionError: In test_assert_no_logs(), the follow messages were unexpectedly logged:\n                    INFO:foo:first message\n                    ERROR:foo.bar:second message\n\n            \"\"\"\n            logging.getLogger('foo').info('first message')\n            logging.getLogger('foo.bar').error('second message')\n\nLoggingTestCase Examples\n========================\nExample1\n--------\n\n``examples/loggingtestcase_example.py``\n\n::\n\n    import unittest\n    import logging\n\n    import loggingtestcase\n\n\n    class LoggingTestCaseExample(loggingtestcase.LoggingTestCase):\n\n        def __init__(self, methodName='runTest', testlogger=None, testlevel=None):\n            \"\"\"\n            To change the logger or log level, override __init__.\n            By default, the root logger is used and the log level is logging.INFO.\n            \"\"\"\n            # testlevel = logging.ERROR\n            super().__init__(methodName, testlogger, testlevel)\n\n        def setUp(self):\n            self.logger = logging.getLogger(__name__)\n            pass\n\n        def test_pass(self):\n            \"\"\"\n            Run a test that logs an info message and\n            verify the info is correctly logged.\n\n            Notice that the info message is not logged to the console.\n            When all your tests pass, your console output is nice and clean.\n            \"\"\"\n            self.logger.info(\"Starting request...\")\n            self.logger.info(\"Done with request.\")\n            self.assertListEqual(self.captured_logs.output,\n                                 ['INFO:examples.loggingtestcase_example:Starting request...',\n                                  'INFO:examples.loggingtestcase_example:Done with request.'])\n\n        def test_fail(self):\n            \"\"\"\n            Run a test that fails.\n\n            Notice that the error message is logged to the console.\n            This allows for easier debugging.\n\n            Here is the output:\n            ======================================================================\n            ERROR: test_fail (examples.example1.Example1)\n            ----------------------------------------------------------------------\n            Traceback (most recent call last):\n              File \"D:\\Git\\logging-test-case\\examples\\loggingtestcase_example.py.py\", line 61,\n              in test_fail raise FileNotFoundError(\"Failed to open file.\")\n            FileNotFoundError: Failed to open file.\n\n            ERROR:examples.example1:Failed to open file.\n            ----------------------------------------------------------------------\n            \"\"\"\n            self.logger.error(\"Failed to open file.\")\n            raise FileNotFoundError(\"Failed to open file.\")\n\n\n    if __name__ == \"__main__\":\n        unittest.main()\n\nIn the above example, notice how ``test_pass()`` and ``test_fail()`` do\nnot have any function decorators or context managers. The captured logs\nare automatically available in ``self.captured_logs.output``.\n\nExample2 - assertNoLogs\n-----------------------\n\n``examples/assertnologs_example1.py``\n\n::\n\n    import unittest\n    import logging\n\n    import loggingtestcase\n\n\n    class AssertNoLogsExample(loggingtestcase.LoggingTestCase):\n        \"\"\"Example on how to use LoggingTestCase and no logging.\"\"\"\n\n        def __init__(self, methodName='runTest', testlogger=None, testlevel=None):\n            \"\"\"\n            To change the logger or log level, override __init__.\n            By default, the root logger is used and the log level is logging.INFO.\n            \"\"\"\n            # testlevel = logging.ERROR\n            super().__init__(methodName, testlogger, testlevel)\n\n        def setUp(self):\n            self.logger = logging.getLogger(__name__)\n\n        def test_assert_no_logs_fail(self):\n            \"\"\"The test fails because logs are emitted.\n\n            Here is the output:\n            E               AssertionError: The follow messages were unexpectedly logged:\n            E                   ERROR:examples.assertnologs_example1:first message\n            E                   ERROR:examples.assertnologs_example1:second message\n\n            \"\"\"\n            with self.assertNoLogs():\n                self.logger.error('first message')\n                self.logger.error('second message')\n\n        def test_assert_no_logs_pass(self):\n            \"\"\"The test passes because no logs are emitted inside the context manager.\"\"\"\n            self.logger.error('first message')\n            with self.assertNoLogs():\n                pass\n            self.logger.error('second message')\n\n\n    if __name__ == \"__main__\":\n        unittest.main()\n\nChangelog\n=========\n\nrelease-1.4.1\n-------------\n* Fixed example in ``README.rst``.  Thanks to julianstirling!\n\nrelease-1.4\n-----------\n* Added support for verifying no logs are emitted during a test.\n    - Added method ``assertNoLogs()`` to class ``LoggingTestCase``.\n    - Added parameter ``assert_no_logs`` to function decorator ``capturelogs``.\n\nrelease-1.3\n-----------\n* Support for Python 3.4, 3.5, and 3.6.\n    -  Previously only Python 3.6 worked.\n* Support for pytest.\n    - Previously only unittest worked.  Now both unittest and pytest work.\n\nThanks to jayvdb on GitHub for providing both fixes!\n\nrelease-1.2\n-----------\nFixed the following error on Python < 3.6:\n\n::\n\n    /usr/local/lib/python3.5/dist-packages/loggingtestcase/capturelogs.py:31: in <module>\n        from enum import Enum, auto\n    E   ImportError: cannot import name 'auto'\n\nThis is because ``enum.auto()`` is new in Python 3.6.  To preserve backward compatibility,\n``auto()`` is no longer used.\n\nrelease-1.1.2\n-------------\n\nAdded ``README.rst`` so this readme shows up on PyPI.\n\nrelease-1.1\n-----------\n\nAdded ``@capturelogs``.\n\nrelease-1.0\n-----------\n\nAdded ``LoggingTestCase``.\n\nTests\n=====\n\nManual Tests\n------------\n\n``tests/manual.py``\n~~~~~~~~~~~~~~~~~~~\n\nRun this file manually. All the tests are commented out. Uncomment and\nrun each test one at a time. Verify the console output.\n\nThis module is not named ``manual_test.py`` because these tests are not\nmeant to be run automatically.\n\nAutomated Tests\n---------------\n\nTo run all the tests from the command line, simply use pytest:\n\n::\n\n    pytest\n\ntests/loggingtestcase\\_test.py\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nThis module tests class ``LoggingTestCase``. It uses\n``subprocess.check_output`` to run each test case one at a time,\ncapturing the output. The output is examined to verify it is correct.\n``loggingtestcase_test.py`` run tests in module\n``simpleloggingtests.py``.\n\nEven though automated tests are included, it is still a good idea to run\nthe manual tests and visually look at the output of each test case.\n\ntests/assertnologs\\_test.py\n~~~~~~~~~~~~~~~~~~~~~~~~~~~\nTests context manager ``assertNoLogs`` in class ``LoggingTestCase``.\n\ntests/capturelogs\\_test.py\n~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nThis module tests ``@capturelogs``, defined in\n``loggingtestcase/capturelogs.py``.\n\n\n",
    "description_content_type": "",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/chadrosenquist/logging-test-case",
    "keywords": "unit testing log files logging regression logging-test-case loggingtestcase",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "logging-test-case",
    "package_url": "https://pypi.org/project/logging-test-case/",
    "platform": "",
    "project_url": "https://pypi.org/project/logging-test-case/",
    "project_urls": {
      "Homepage": "https://github.com/chadrosenquist/logging-test-case"
    },
    "release_url": "https://pypi.org/project/logging-test-case/1.4.1/",
    "requires_dist": null,
    "requires_python": ">=3.4",
    "summary": "Provides class LoggingTestCase to help test log files.",
    "version": "1.4.1",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 7322567,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "c9b1ef1dbc1a3fe7e32dd2749c4c0e5957dbaad8524c07a7666262a8094b2a78",
        "md5": "d2ca36a8efd4a71884e00c3e48f867f2",
        "sha256": "8f631d96af87c4bafb18c5e322bde577465217f22e54da25d8a11f585034ff90"
      },
      "downloads": -1,
      "filename": "logging_test_case-1.4.1-py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "d2ca36a8efd4a71884e00c3e48f867f2",
      "packagetype": "bdist_wheel",
      "python_version": "py3",
      "requires_python": ">=3.4",
      "size": 10994,
      "upload_time": "2020-05-25T22:27:34",
      "upload_time_iso_8601": "2020-05-25T22:27:34.953198Z",
      "url": "https://files.pythonhosted.org/packages/c9/b1/ef1dbc1a3fe7e32dd2749c4c0e5957dbaad8524c07a7666262a8094b2a78/logging_test_case-1.4.1-py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "6ef718cd4bc29887b3c25972167ffba32993c18530b1022a8136e2353631fbf7",
        "md5": "9bb10c66e0ed958acf527d4a6784755b",
        "sha256": "62905a0ca0c81f365c0b4a21092a729945a6679444ca654304823457795ffca3"
      },
      "downloads": -1,
      "filename": "logging-test-case-1.4.1.tar.gz",
      "has_sig": false,
      "md5_digest": "9bb10c66e0ed958acf527d4a6784755b",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": ">=3.4",
      "size": 9005,
      "upload_time": "2020-05-25T22:27:36",
      "upload_time_iso_8601": "2020-05-25T22:27:36.136139Z",
      "url": "https://files.pythonhosted.org/packages/6e/f7/18cd4bc29887b3c25972167ffba32993c18530b1022a8136e2353631fbf7/logging-test-case-1.4.1.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}