{
  "info": {
    "author": "Morgan Bohn",
    "author_email": "morgan.bohn@unistra.fr",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 4 - Beta",
      "Environment :: Web Environment",
      "Framework :: Django",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3"
    ],
    "description": "django-rest-custom-exceptions\n======================================\n\nCustom exceptions for django rest framework\n\nCompatibility\n-------------\n\nwork with :\n * Python 2.7, 3.3, 3.4\n * Dango 1.7, 1.8\n * Django Rest Framework >= 3.0\n\nInstallation\n------------\n\nInstall the package from pypi: ::\n\n    pip install djangorestframework-custom-exceptions\n\nAdd the application in your django settings: ::\n\n    INSTALLED_APPS = ('rest_framework_custom_exceptions',)\n\nConfigure your rest framework : ::\n\n    REST_FRAMEWORK = {\n        'EXCEPTION_HANDLER': 'rest_framework_custom_exceptions.exceptions.simple_error_handler'\n    }\n\nExample\n-------\n\nThe simple error handler show exceptions like this : ::\n    \n    {\n        \"error\": \"Not found\"\n    }",
    "description_content_type": null,
    "docs_url": null,
    "download_url": "https://pypi.python.org/pypi/djangorestframework-custom-exceptions",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/unistra/django-rest-framework-custom-exceptions",
    "keywords": "django,REST,rest_framework,exceptions",
    "license": "UNKNOWN",
    "maintainer": null,
    "maintainer_email": null,
    "name": "djangorestframework-custom-exceptions",
    "package_url": "https://pypi.org/project/djangorestframework-custom-exceptions/",
    "platform": "UNKNOWN",
    "project_url": "https://pypi.org/project/djangorestframework-custom-exceptions/",
    "project_urls": {
      "Download": "https://pypi.python.org/pypi/djangorestframework-custom-exceptions",
      "Homepage": "https://github.com/unistra/django-rest-framework-custom-exceptions"
    },
    "release_url": "https://pypi.org/project/djangorestframework-custom-exceptions/1.0.1/",
    "requires_dist": null,
    "requires_python": null,
    "summary": "Custom exceptions for Django REST Framework",
    "version": "1.0.1",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 6174236,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "ed30d2386fc97ca85331ea7ab1d87da8dad5506206ea0f0c0c9796d3194915b2",
        "md5": "69b883cec15df1f5cc3aa353151ab838",
        "sha256": "1ce99a2bbc259d4d405bbe3417281e960f5fe5b2d70a622b1d151151a9443e31"
      },
      "downloads": -1,
      "filename": "djangorestframework-custom-exceptions-1.0.1.tar.gz",
      "has_sig": false,
      "md5_digest": "69b883cec15df1f5cc3aa353151ab838",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 10130,
      "upload_time": "2016-01-18T10:28:59",
      "upload_time_iso_8601": "2016-01-18T10:28:59.989542Z",
      "url": "https://files.pythonhosted.org/packages/ed/30/d2386fc97ca85331ea7ab1d87da8dad5506206ea0f0c0c9796d3194915b2/djangorestframework-custom-exceptions-1.0.1.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}