{
  "info": {
    "author": "Morgan Bohn",
    "author_email": "morgan.bohn@unistra.fr",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 4 - Beta",
      "Environment :: Web Environment",
      "Framework :: Django",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3"
    ],
    "description": "django-rest-custom-exceptions\n======================================\n\nCustom exceptions for django rest framework\n\nCompatibility\n-------------\n\nwork with :\n * Python 2.7 / 3.4\n * Dango 1.6 / 1.7\n * Django Rest Framework 2.4 / 3.0\n\nInstallation\n------------\n\nInstall the package from pypi: ::\n\n    pip install djangorestframework-custom-exceptions\n\nAdd the application in your django settings: ::\n\n    DJANGO_APPS = ('rest_framework_custom_exceptions',)\n\nConfigure your rest framework : ::\n\n    REST_FRAMEWORK = {\n        'EXCEPTION_HANDLER': 'rest_framework_custom_exceptions.exceptions.simple_error_handler'\n    }",
    "description_content_type": null,
    "docs_url": null,
    "download_url": "https://pypi.python.org/pypi/djangorestframework-custom-exceptions",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/unistra/django-rest-framework-custom-exceptions",
    "keywords": "django,REST,rest_framework,exceptions",
    "license": "UNKNOWN",
    "maintainer": null,
    "maintainer_email": null,
    "name": "djangorestframework-custom-exceptions",
    "package_url": "https://pypi.org/project/djangorestframework-custom-exceptions/",
    "platform": "UNKNOWN",
    "project_url": "https://pypi.org/project/djangorestframework-custom-exceptions/",
    "project_urls": {
      "Download": "https://pypi.python.org/pypi/djangorestframework-custom-exceptions",
      "Homepage": "https://github.com/unistra/django-rest-framework-custom-exceptions"
    },
    "release_url": "https://pypi.org/project/djangorestframework-custom-exceptions/1.0.0/",
    "requires_dist": null,
    "requires_python": null,
    "summary": "Custom exceptions for Django REST Framework",
    "version": "1.0.0",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 6174236,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "faec974cb1aacfb0ef1e90013247caaaf84e92a645c1eec26f50eeac76f9ece6",
        "md5": "a59789caa4556ee9ecd445179363411d",
        "sha256": "70bd2106674f3fe0eeb0c224b82a3ab03113f1aae834d808b630c968178f3ac8"
      },
      "downloads": -1,
      "filename": "djangorestframework-custom-exceptions-1.0.0.tar.gz",
      "has_sig": false,
      "md5_digest": "a59789caa4556ee9ecd445179363411d",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 9325,
      "upload_time": "2015-05-20T16:10:06",
      "upload_time_iso_8601": "2015-05-20T16:10:06.369533Z",
      "url": "https://files.pythonhosted.org/packages/fa/ec/974cb1aacfb0ef1e90013247caaaf84e92a645c1eec26f50eeac76f9ece6/djangorestframework-custom-exceptions-1.0.0.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}